### ISSUE TITLE
Rewrite matrices class to utilize better cache access

### ISSUE THREAD

**Issue by sumiya11** [x3042/Exact-reduction-of-ODE-systems#10]

**Comment by sumiya11** [comment]
1. Use continuous (or even static) memory for vectors
2. Specify the algorithm for finite fields *exclusively*. Whenever a QQ computation is requested, reduce to modular computations

**Comment by pogudingleb** [comment]
Comment to the second item: in CLUE, we found out that quite often it is actually faster to work over QQ, see Table 1 on page 9 in https://arxiv.org/pdf/2004.11961.pdf
