### ISSUE TITLE
Separate types conversion from main logic

### ISSUE THREAD

**Issue by sumiya11** [x3042/Exact-reduction-of-ODE-systems#3]

**Comment by pogudingleb** [comment]
What does this mean?

**Comment by sumiya11** [comment]
@pogudingleb We want to elude multiplie single element type conversions during high loaded computations, such as `convert` in 

https://github.com/x3042/Exact-reduction-of-ODE-systems/blob/e5c2f50b361395a06d0dc3edcc336111cf2d71cc/src/structs/sparsik.jl#L316
or coercing into field in 
https://github.com/x3042/Exact-reduction-of-ODE-systems/blob/e5c2f50b361395a06d0dc3edcc336111cf2d71cc/src/gizmos.jl#L60

What could be optimal here is to perform vectorized type conversion for each element first, and the rest of the computations on it after

**Comment by pogudingleb** [comment]
This makes sense but is this really a bottleneck?

**Comment by sumiya11** [comment]
closed as being outdated after the last refactor
